//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestGateway.OrderService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateOrderRequest", Namespace="http://schemas.datacontract.org/2004/07/SOAP_Order_Service.Contracts")]
    public partial class CreateOrderRequest : object
    {
        
        private int ClientIdField;
        
        private RestGateway.OrderService.ProductItem[] ProductsField;
        
        private RestGateway.OrderService.Address AddressField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientId
        {
            get
            {
                return this.ClientIdField;
            }
            set
            {
                this.ClientIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RestGateway.OrderService.ProductItem[] Products
        {
            get
            {
                return this.ProductsField;
            }
            set
            {
                this.ProductsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public RestGateway.OrderService.Address Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/SOAP_Order_Service.Models")]
    public partial class Address : object
    {
        
        private string StreetField;
        
        private string CityField;
        
        private string StateField;
        
        private string ZipCodeField;
        
        private string CountryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street
        {
            get
            {
                return this.StreetField;
            }
            set
            {
                this.StreetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string ZipCode
        {
            get
            {
                return this.ZipCodeField;
            }
            set
            {
                this.ZipCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductItem", Namespace="http://schemas.datacontract.org/2004/07/SOAP_Order_Service.Models")]
    public partial class ProductItem : object
    {
        
        private int ProductIdField;
        
        private int QuantityField;
        
        private decimal UnitPriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId
        {
            get
            {
                return this.ProductIdField;
            }
            set
            {
                this.ProductIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UnitPrice
        {
            get
            {
                return this.UnitPriceField;
            }
            set
            {
                this.UnitPriceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateOrderResponse", Namespace="http://schemas.datacontract.org/2004/07/SOAP_Order_Service.Contracts")]
    public partial class CreateOrderResponse : object
    {
        
        private int OrderIdField;
        
        private RestGateway.OrderService.OrderStatus StatusField;
        
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId
        {
            get
            {
                return this.OrderIdField;
            }
            set
            {
                this.OrderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RestGateway.OrderService.OrderStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                this.CreatedDateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderStatus", Namespace="http://schemas.datacontract.org/2004/07/SOAP_Order_Service.Models")]
    public enum OrderStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CREATED = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PAID = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SHIPPED = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DELIVERED = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CalculateOrderTotalRequest", Namespace="http://schemas.datacontract.org/2004/07/SOAP_Order_Service.Contracts")]
    public partial class CalculateOrderTotalRequest : object
    {
        
        private int OrderIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId
        {
            get
            {
                return this.OrderIdField;
            }
            set
            {
                this.OrderIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CalculateOrderTotalResponse", Namespace="http://schemas.datacontract.org/2004/07/SOAP_Order_Service.Contracts")]
    public partial class CalculateOrderTotalResponse : object
    {
        
        private decimal SubtotalField;
        
        private decimal TaxesField;
        
        private decimal DiscountField;
        
        private decimal ShippingField;
        
        private decimal TotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Subtotal
        {
            get
            {
                return this.SubtotalField;
            }
            set
            {
                this.SubtotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Taxes
        {
            get
            {
                return this.TaxesField;
            }
            set
            {
                this.TaxesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal Discount
        {
            get
            {
                return this.DiscountField;
            }
            set
            {
                this.DiscountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal Shipping
        {
            get
            {
                return this.ShippingField;
            }
            set
            {
                this.ShippingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateOrderStatusRequest", Namespace="http://schemas.datacontract.org/2004/07/SOAP_Order_Service.Contracts")]
    public partial class UpdateOrderStatusRequest : object
    {
        
        private int OrderIdField;
        
        private RestGateway.OrderService.OrderStatus NewStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId
        {
            get
            {
                return this.OrderIdField;
            }
            set
            {
                this.OrderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public RestGateway.OrderService.OrderStatus NewStatus
        {
            get
            {
                return this.NewStatusField;
            }
            set
            {
                this.NewStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateOrderStatusResponse", Namespace="http://schemas.datacontract.org/2004/07/SOAP_Order_Service.Contracts")]
    public partial class UpdateOrderStatusResponse : object
    {
        
        private int OrderIdField;
        
        private RestGateway.OrderService.OrderStatus PreviousStatusField;
        
        private RestGateway.OrderService.OrderStatus NewStatusField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId
        {
            get
            {
                return this.OrderIdField;
            }
            set
            {
                this.OrderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RestGateway.OrderService.OrderStatus PreviousStatus
        {
            get
            {
                return this.PreviousStatusField;
            }
            set
            {
                this.PreviousStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public RestGateway.OrderService.OrderStatus NewStatus
        {
            get
            {
                return this.NewStatusField;
            }
            set
            {
                this.NewStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOrderDetailsRequest", Namespace="http://schemas.datacontract.org/2004/07/SOAP_Order_Service.Contracts")]
    public partial class GetOrderDetailsRequest : object
    {
        
        private int OrderIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId
        {
            get
            {
                return this.OrderIdField;
            }
            set
            {
                this.OrderIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOrderDetailsResponse", Namespace="http://schemas.datacontract.org/2004/07/SOAP_Order_Service.Contracts")]
    public partial class GetOrderDetailsResponse : object
    {
        
        private RestGateway.OrderService.Order OrderField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RestGateway.OrderService.Order Order
        {
            get
            {
                return this.OrderField;
            }
            set
            {
                this.OrderField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/SOAP_Order_Service.Models")]
    public partial class Order : object
    {
        
        private int OrderIdField;
        
        private int ClientIdField;
        
        private RestGateway.OrderService.ProductItem[] ProductsField;
        
        private RestGateway.OrderService.Address AddressField;
        
        private RestGateway.OrderService.OrderStatus StatusField;
        
        private System.DateTime CreatedDateField;
        
        private decimal SubtotalField;
        
        private decimal TaxesField;
        
        private decimal DiscountField;
        
        private decimal ShippingField;
        
        private decimal TotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId
        {
            get
            {
                return this.OrderIdField;
            }
            set
            {
                this.OrderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ClientId
        {
            get
            {
                return this.ClientIdField;
            }
            set
            {
                this.ClientIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public RestGateway.OrderService.ProductItem[] Products
        {
            get
            {
                return this.ProductsField;
            }
            set
            {
                this.ProductsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public RestGateway.OrderService.Address Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public RestGateway.OrderService.OrderStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                this.CreatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public decimal Subtotal
        {
            get
            {
                return this.SubtotalField;
            }
            set
            {
                this.SubtotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public decimal Taxes
        {
            get
            {
                return this.TaxesField;
            }
            set
            {
                this.TaxesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public decimal Discount
        {
            get
            {
                return this.DiscountField;
            }
            set
            {
                this.DiscountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public decimal Shipping
        {
            get
            {
                return this.ShippingField;
            }
            set
            {
                this.ShippingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public decimal Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soaporderservice.com/", ConfigurationName="RestGateway.OrderService.IOrderService")]
    public interface IOrderService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soaporderservice.com/IOrderService/CreateOrder", ReplyAction="http://soaporderservice.com/IOrderService/CreateOrderResponse")]
        System.Threading.Tasks.Task<RestGateway.OrderService.CreateOrderResponse> CreateOrderAsync(RestGateway.OrderService.CreateOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soaporderservice.com/IOrderService/CalculateOrderTotal", ReplyAction="http://soaporderservice.com/IOrderService/CalculateOrderTotalResponse")]
        System.Threading.Tasks.Task<RestGateway.OrderService.CalculateOrderTotalResponse> CalculateOrderTotalAsync(RestGateway.OrderService.CalculateOrderTotalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soaporderservice.com/IOrderService/UpdateOrderStatus", ReplyAction="http://soaporderservice.com/IOrderService/UpdateOrderStatusResponse")]
        System.Threading.Tasks.Task<RestGateway.OrderService.UpdateOrderStatusResponse> UpdateOrderStatusAsync(RestGateway.OrderService.UpdateOrderStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soaporderservice.com/IOrderService/GetOrderDetails", ReplyAction="http://soaporderservice.com/IOrderService/GetOrderDetailsResponse")]
        System.Threading.Tasks.Task<RestGateway.OrderService.GetOrderDetailsResponse> GetOrderDetailsAsync(RestGateway.OrderService.GetOrderDetailsRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IOrderServiceChannel : RestGateway.OrderService.IOrderService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class OrderServiceClient : System.ServiceModel.ClientBase<RestGateway.OrderService.IOrderService>, RestGateway.OrderService.IOrderService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OrderServiceClient() : 
                base(OrderServiceClient.GetDefaultBinding(), OrderServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IOrderService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrderServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(OrderServiceClient.GetBindingForEndpoint(endpointConfiguration), OrderServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrderServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OrderServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrderServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OrderServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<RestGateway.OrderService.CreateOrderResponse> CreateOrderAsync(RestGateway.OrderService.CreateOrderRequest request)
        {
            return base.Channel.CreateOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<RestGateway.OrderService.CalculateOrderTotalResponse> CalculateOrderTotalAsync(RestGateway.OrderService.CalculateOrderTotalRequest request)
        {
            return base.Channel.CalculateOrderTotalAsync(request);
        }
        
        public System.Threading.Tasks.Task<RestGateway.OrderService.UpdateOrderStatusResponse> UpdateOrderStatusAsync(RestGateway.OrderService.UpdateOrderStatusRequest request)
        {
            return base.Channel.UpdateOrderStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<RestGateway.OrderService.GetOrderDetailsResponse> GetOrderDetailsAsync(RestGateway.OrderService.GetOrderDetailsRequest request)
        {
            return base.Channel.GetOrderDetailsAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IOrderService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                
                // Configuración explícita para SOAP 1.1
                result.MessageEncoding = System.ServiceModel.WSMessageEncoding.Text;
                result.TextEncoding = System.Text.Encoding.UTF8;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.None;
                
                // Configuración de límites
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                
                // Timeouts
                result.OpenTimeout = System.TimeSpan.FromMinutes(1);
                result.CloseTimeout = System.TimeSpan.FromMinutes(1);
                result.SendTimeout = System.TimeSpan.FromMinutes(1);
                result.ReceiveTimeout = System.TimeSpan.FromMinutes(10);
                
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IOrderService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:5000/OrderService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OrderServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IOrderService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OrderServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IOrderService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IOrderService,
        }
    }
}
